name: Android CI

on:
  push:
    branches:
        - '*'
        - 'renovate/**'
  pull_request:
  workflow_dispatch:

jobs:
  linux-build:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: liberica
          cache: 'gradle'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.10.0
        with:
          gradle-home-cache-cleanup: true
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
        with:
          min-wrapper-count: 2
          allow-snapshots: false
      - name: Spotless check
        run: ./gradlew spotlessCheck
      - name: Build debug apk with Gradle
        run: ./gradlew assembleDebug
      - name: Upload debug apk
        uses: actions/upload-artifact@v3
        with:
          name: app-debug-${{ github.sha }}.apk
          path: project/app/build/outputs/apk/debug/app-debug.apk
